### ISSUE TITLE
Cannot build - getting an unresolved imports error

### ISSUE THREAD

**Issue by conormdowney** [CardinalBytes/daemonize-me#7] opened 2022-03-15 15:00 UTC
Im trying to use the crate in a simple project just to start a daemon to do some =thing simple. 
I have added daemonize-me = "1.0" to my Cargo.toml.
When I run cargo build I get the following: 

 ```
Compiling daemonize-me v1.0.0
error[E0432]: unresolved imports `libc::prctl`, `libc::PR_SET_NAME`
 --> /Users/conordowney/.cargo/registry/src/github.com-1ecc6299db9ec823/daemonize-me-1.0.0/src/ffi.rs:6:12
  |
6 | use libc::{prctl, PR_SET_NAME};
  |            ^^^^^  ^^^^^^^^^^^ no `PR_SET_NAME` in the root
  |            |
  |            no `prctl` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `daemonize-me` due to previous error
```

My program is just a hello world. I just wanted to see if it would build with the package included. Any idea what might be wrong?

**Comment by tqwewe** [comment] 2022-03-19 13:06
I am also getting this error. I am on macos

**Comment by xadaemon** [comment] 2022-03-21 20:36
Hello, this flew under my radar, so I didn't respond in a timely manner, I'm investigating the issue ~~and will likely release a maintenance 1.1 release and yank 1.0 in the next day or so~~ and will release 1.0.1 as maintenance release that fixes this mac specific issue if possible.

**Comment by xadaemon** [comment] 2022-03-21 20:58
@conormdowney I assume you are on macos by the path on your excerpt, the problem was I overlooked one of the imports, that is not available in macos, I don't have access to a mac to test this one out, so please try pointing cargo at `maintenance/1-0-0-import-errors` and confirm if the issue is fixed.

@tqwewe if you could test this out too.

Regards

**Comment by tqwewe** [comment] 2022-03-21 21:03
Copying the example from the readme and using `daemonize-me = { git = "https://github.com/DarthUdp/daemonize-me", branch = "maintenance/1-0-0-import-errors" }`, I immediately get segmentation fault when I run the app.

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.52s
     Running `target/debug/daemontest`
[1]    74897 segmentation fault  cargo run
```

**Comment by xadaemon** [comment] 2022-03-21 21:04
@tqwewe can you provide me more details about your mac? Namely:
* OS version;
* Intel or M1;

**Comment by tqwewe** [comment] 2022-03-21 21:06
Sure!
- macOS Monterey 12.3
- Intel

**Comment by xadaemon** [comment] 2022-03-21 21:12
@tqwewe Thanks, can you do a `cargo build --release` and run the resulting binary with `dtruss` so we can get an idea where it is segfaulting, my best guess is some of the syscalls in `src/ffi.rs`.

Regards

**Comment by tqwewe** [comment] 2022-03-21 21:15
I've ran it and attached the output.
<details>
<summary><code>dtruss ./target/release/daemontest</code></summary>

```
$ sudo dtruss ./target/release/daemontest          
dtrace: system integrity protection is on, some features will not be available

SYSCALL(args)            = return
kdebug_typefilter(0x7FF7B6972448, 0x7FF7B6972440, 0x0)           = 0 0
kdebug_trace64(0x2BDC0011, 0x0, 0x0, 0x0, 0x0)           = 0 0
access("/AppleInternal/XBS/.isChrooted\0", 0x0, 0x0)             = -1 2
kdebug_trace64(0x2BDC0010, 0x1, 0x0, 0x0, 0x0)           = 0 0
kdebug_trace64(0x2BDC0010, 0x2, 0x0, 0x0, 0x0)           = 0 0
bsdthread_register(0x7FF808431000, 0x7FF808430FEC, 0x2000)               = 1073742303 0
kdebug_trace64(0x2BDC0010, 0x3, 0x0, 0x0, 0x0)           = 0 0
kdebug_trace64(0x2BDC0010, 0x4, 0x0, 0x0, 0x0)           = 0 0
shm_open(0x7FF8082FFF5D, 0x0, 0x82FE7BA)                 = 3 0
fstat64(0x3, 0x7FF7B6971E20, 0x0)                = 0 0
mmap(0x0, 0x2000, 0x1, 0x40001, 0x3, 0x0)                = 0x10970A000 0
close(0x3)               = 0 0
ioctl(0x2, 0x4004667A, 0x7FF7B6971ED4)           = 0 0
mprotect(0x109711000, 0x1000, 0x0)               = 0 0
mprotect(0x10971D000, 0x1000, 0x0)               = 0 0
mprotect(0x10971E000, 0x1000, 0x0)               = 0 0
mprotect(0x10972A000, 0x1000, 0x0)               = 0 0
mprotect(0x10972B000, 0x1000, 0x0)               = 0 0
mprotect(0x109737000, 0x1000, 0x0)               = 0 0
mprotect(0x10970C000, 0x90, 0x1)                 = 0 0
mprotect(0x10970C000, 0x90, 0x3)                 = 0 0
mprotect(0x10970C000, 0x90, 0x1)                 = 0 0
mprotect(0x109738000, 0x1000, 0x1)               = 0 0
mprotect(0x109739000, 0x90, 0x1)                 = 0 0
mprotect(0x109739000, 0x90, 0x3)                 = 0 0
mprotect(0x109739000, 0x90, 0x1)                 = 0 0
mprotect(0x10970C000, 0x90, 0x3)                 = 0 0
mprotect(0x10970C000, 0x90, 0x1)                 = 0 0
mprotect(0x109738000, 0x1000, 0x3)               = 0 0
mprotect(0x109738000, 0x1000, 0x1)               = 0 0
kdebug_trace64(0x2BDC0010, 0x5, 0x0, 0x0, 0x0)           = 0 0
kdebug_trace64(0x2BDC0010, 0x6, 0x0, 0x0, 0x0)           = 0 0
kdebug_trace64(0x2BDC0010, 0x7, 0x0, 0x0, 0x0)           = 0 0
issetugid(0x0, 0x0, 0x0)                 = 0 0
getentropy(0x7FF7B6971CD0, 0x20, 0x0)            = 0 0
getentropy(0x7FF7B6971D30, 0x40, 0x0)            = 0 0
kdebug_trace64(0x2BDC0010, 0x8, 0x0, 0x0, 0x0)           = 0 0
getpid(0x0, 0x0, 0x0)            = 76396 0
stat64("/AppleInternal\0", 0x7FF7B69723F0, 0x0)          = -1 2
csops_audittoken(0x12A6C, 0x7, 0x7FF7B6971F20)           = -1 22
proc_info(0x2, 0x12A6C, 0xD)             = 64 0
kdebug_trace64(0x2BDC0010, 0x9, 0x0, 0x0, 0x0)           = 0 0
kdebug_trace64(0x2BDC0010, 0xA, 0x0, 0x0, 0x0)           = 0 0
csops_audittoken(0x12A6C, 0x7, 0x7FF7B6972010)           = -1 22
kdebug_trace64(0x2BDC0010, 0xB, 0x0, 0x0, 0x0)           = 0 0
kdebug_trace64(0x2BDC0010, 0xC, 0x0, 0x0, 0x0)           = 0 0
kdebug_trace64(0x2BDC0010, 0xD, 0x0, 0x0, 0x0)           = 0 0
sysctlbyname(kern.osvariant_status, 0x15, 0x7FF7B6972440, 0x7FF7B6972438, 0x0)           = 0 0
csops(0x12A6C, 0x0, 0x7FF7B6972474)              = 0 0
kdebug_trace64(0x2BDC0012, 0x0, 0x0, 0x0, 0x0)           = 0 0
mprotect(0x109606000, 0x100000, 0x1)             = 0 0
fcntl(0x0, 0x1, 0x1)             = 0 0
fcntl(0x1, 0x1, 0x0)             = 0 0
fcntl(0x2, 0x1, 0x0)             = 0 0
sigaction(0xD, 0x7FF7B6973498, 0x7FF7B69734C0)           = 0 0
sigaction(0xB, 0x0, 0x7FF7B69735A0)              = 0 0
sigaction(0xB, 0x7FF7B69734C8, 0x0)              = 0 0
sigaction(0xA, 0x0, 0x7FF7B69735A0)              = 0 0
sigaction(0xA, 0x7FF7B69734C8, 0x0)              = 0 0
sigaltstack(0x0, 0x7FF7B69734B0, 0x0)            = 0 0
dtrace: error on enabled probe ID 1717 (ID 581: syscall::sysctl:return): invalid kernel access in action #10 at DIF offset 28
mmap(0x0, 0x21000, 0x3, 0x41002, 0xFFFFFFFFFFFFFFFF, 0x0)                = 0x109741000 0
mprotect(0x109741000, 0x1000, 0x0)               = 0 0
sigaltstack(0x7FF7B69734B0, 0x0, 0x0)            = 0 0
getrlimit(0x1003, 0x7FF7B69734B8, 0x0)           = 0 0
mmap(0x7FF7B6174000, 0x1000, 0x3, 0x41012, 0xFFFFFFFFFFFFFFFF, 0x0)              = 0x7FF7B6174000 0
mprotect(0x7FF7B6174000, 0x1000, 0x0)            = 0 0
open("info.log\0", 0x1000601, 0x1B6)             = 3 0
open("err.log\0", 0x1000601, 0x1B6)              = 4 0
shm_open(0x7FF80AE9A150, 0x0, 0x0)               = 5 0
mmap(0x0, 0x1000, 0x1, 0x40001, 0x5, 0x0)                = 0x109762000 0
close_nocancel(0x5)              = 0 0
open_nocancel("/etc/.mdns_debug\0", 0x0, 0x0)            = -1 2
issetugid(0x0, 0x0, 0x0)                 = 0 0
issetugid(0x0, 0x0, 0x0)                 = 0 0
getattrlist("/private/tmp/daemontest/target/release/daemontest\0", 0x7FF7B69725C0, 0x7FF7B69725D8)               = 0 0
access("/private/tmp/daemontest/target/release\0", 0x4, 0x0)             = 0 0
open("/private/tmp/daemontest/target/release\0", 0x0, 0x0)               = 5 0
fstat64(0x5, 0x7FA49D704400, 0x0)                = 0 0
csrctl(0x0, 0x7FF7B697284C, 0x4)                 = -1 1
fgetattrlist(0x5, 0x7FF7B6972860, 0x7FF7B6972880)                = 0 0
__mac_syscall(0x7FF811B28829, 0x2, 0x7FF7B6972880)               = 0 0
fcntl(0x5, 0x32, 0x7FF7B69724F0)                 = 0 0
close(0x5)               = 0 0
open("/private/tmp/daemontest/target/release/Info.plist\0", 0x0, 0x0)            = -1 2
proc_info(0x2, 0x12A6C, 0x11)            = 56 0
proc_info(0x2, 0x12A6C, 0x11)            = 56 0
mprotect(0x109606000, 0x100000, 0x3)             = 0 0
mprotect(0x109606000, 0x100000, 0x1)             = 0 0
mprotect(0x109606000, 0x100000, 0x3)             = 0 0
mprotect(0x109606000, 0x100000, 0x1)             = 0 0
dtrace: error on enabled probe ID 1717 (ID 581: syscall::sysctl:return): invalid kernel access in action #10 at DIF offset 28
issetugid(0x0, 0x0, 0x0)                 = 0 0
openat(0xFFFFFFFFFFFFFFFE, "/Library/Preferences/Logging/com.apple.diagnosticd.filter.plist\0", 0x1000104, 0x0)          = -1 2
sigaction(0xB, 0x1097619D8, 0x0)                 = 0 0
sigreturn(0x109761F48, 0x1E, 0xF9917FE71B9428F7)                 = 0 -2

```
</details>

**Comment by xadaemon** [comment] 2022-03-21 21:21
Thanks I will have a look.

**Comment by xadaemon** [comment] 2022-03-21 21:26
MacOS is quite different from linux, unfortunately, can you try and check `~/Library/Logs/DiagnosticReports` for a crash file? It should have the info we need to get at which syscall is acting up here (if a bit of google foo is correct).

**Comment by xadaemon** [comment] 2022-03-21 21:41
In the meantime I have been looking through the code in `src/ffi.rs` and it's unsafe callsites and the groups and users handling functions look like prime suspects to me. I narrowed it down to the struct bellow.

linux:
```c
struct passwd {
               char   *pw_name;       /* username */
               char   *pw_passwd;     /* user password */
               uid_t   pw_uid;        /* user ID */
               gid_t   pw_gid;        /* group ID */
               char   *pw_gecos;      /* user information */
               char   *pw_dir;        /* home directory */
               char   *pw_shell;      /* shell program */
           };
```
macOS and BSDs:
```c
struct passwd {
                   char    *pw_name;       /* user name */
                   char    *pw_passwd;     /* encrypted password */
                   uid_t   pw_uid;         /* user uid */
                   gid_t   pw_gid;         /* user gid */
                   time_t  pw_change;      /* password change time */
                   char    *pw_class;      /* user access class */
                   char    *pw_gecos;      /* Honeywell login info */
                   char    *pw_dir;        /* home directory */
                   char    *pw_shell;      /* default shell */
                   time_t  pw_expire;      /* account expiration */
                   int     pw_fields;      /* internal: fields filled in */
           };
```
the repo:
https://github.com/DarthUdp/daemonize-me/blob/324556d09aaccb0fe356cbe85903924f27340b38/src/ffi.rs#L23-L33

**Comment by xadaemon** [comment] 2022-03-21 21:45
As you can see the memory rust is allocating for the passwd struct is insuficient on mac and thus the segfault.

Oh the joys of ffi and unsafe code lol.

I will try to update the struct and will need a new re-test @tqwewe, however if this does not work I'm afraid I will have to leave this issue to someone with access to a mac or it will prove an exercise in frustration. I would be able to guide someone on this though.

**Comment by xadaemon** [comment] 2022-03-21 21:57
I made a new commit to that fix branch, can you please do a test @tqwewe?

**Comment by tqwewe** [comment] 2022-03-22 06:37
Yeah this is a difficult one, and I sadly have never debugged a segfault before. But I'm happy to help in any way I can.

I've just run cargo update and run, and the example in the readme ran with no segfault this time! It ran but didn't log anything to the terminal, and the err.log file has `Error, Failed to set gid`.

**Comment by xadaemon** [comment] 2022-03-22 07:06
@tqwewe if you did not run the executable with sudo, it failing to set the gid is expected behaviour as per macOS docs

> The setgid()
> function is permitted if the effective user ID is that of the super user,
> or if the specified group ID is the same as the effective group ID.

https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/setgid.2.html

it's the same for setuid.

So in short:
It's likely failing to drop privileges because there is no privileges to drop.

So I think this seems fixed :)

**Comment by xadaemon** [comment] 2022-03-22 07:40
> Yeah this is a difficult one, and I sadly have never debugged a segfault before. But I'm happy to help in any way I can.
> 
> I've just run cargo update and run, and the example in the readme ran with no segfault this time! It ran but didn't log anything to the terminal, and the err.log file has `Error, Failed to set gid`.

Segfaults are usually the spawn of invalid memory access, thanks to rust you can pretty much pinpoint those to unsafe blocks and functions, unless something has gone VERY wrong. And this is the beauty of rust for systems level code so much easier to find the mistakes.

**Comment by xadaemon** [comment] 2022-03-22 07:58
I have confirmed with a colleague that has a mac that this is working properly, I will close this issue, but feel free to re-open if anything new happens @tqwewe  @conormdowney.

As a final resolution @tqwewe that error on setting the gid should be handled by your application, the example code just crashes on it but if handled your application can proceed as normal.

Regards

**Closed as completed** 2022-03-22 08:00 UTC
Labels: bug, platform-bsd, platform-mac
